In [1]:
from pyspark import SparkContext
from pyspark.sql import SQLContext, Row
import pandas as pd

In [2]:
sc = SparkContext('local')

In [3]:
sqlCtx = SQLContext(sc)

In [4]:
df = sqlCtx.read.csv( 'data/crime_in_seoul.csv',encoding='euc-kr',
                    header=True, inferSchema=True)
df

DataFrame[관서명: string, 살인 발생: int, 살인 검거: int, 강도 발생: int, 강도 검거: int, 강간 발생: int, 강간 검거: int, 절도 발생: string, 절도 검거: string, 폭력 발생: string, 폭력 검거: string]

In [5]:
df.show()

+--------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+
|  관서명|살인 발생|살인 검거|강도 발생|강도 검거|강간 발생|강간 검거|절도 발생|절도 검거|폭력 발생|폭력 검거|
+--------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+
|  중부서|        2|        2|        3|        2|      105|       65|    1,395|      477|    1,355|    1,170|
|  종로서|        3|        3|        6|        5|      115|       98|    1,070|      413|    1,278|    1,070|
|남대문서|        1|        0|        6|        4|       65|       46|    1,153|      382|      869|      794|
|서대문서|        2|        2|        5|        4|      154|      124|    1,812|      738|    2,056|    1,711|
|  혜화서|        3|        2|        5|        4|       96|       63|    1,114|      424|    1,015|      861|
|  용산서|        5|        5|       14|       14|      194|      173|    1,557|      587|    2,050|    1,704|
|  성북서|        2|        2|        2|        1|       86|       71|      953|      409|    1,194|    1,015|
|동대문서|        5|        5|       13|       13|      173|      146|    1,981|      814|    2,548|    2,227|
|  마포서|        8|        8|       14|       10|      294|      247|    2,555|      813|    2,983|    2,519|
|영등포서|       14|       12|       22|       20|      295|      183|    2,964|      978|    3,572|    2,961|
|  성동서|        4|        4|        9|        8|      126|      119|    1,607|      597|    1,612|    1,395|
|  동작서|        5|        5|        9|        5|      285|      139|    1,865|      661|    1,910|    1,587|
|  광진서|        4|        4|       14|       26|      240|      220|    3,026|    1,277|    2,625|    2,180|
|  서부서|        2|        2|        2|        1|       70|       59|      819|      293|    1,192|    1,038|
|  강북서|        7|        8|       14|       13|      153|      126|    1,434|      618|    2,649|    2,348|
|  금천서|        3|        4|        6|        6|      151|      122|    1,567|      888|    2,054|    1,776|
|  중랑서|       13|       12|       11|        9|      187|      148|    2,135|      829|    2,847|    2,407|
|  강남서|        3|        3|       15|       12|      300|      225|    2,411|      984|    2,465|    2,146|
|  관악서|        9|        8|       12|       14|      320|      221|    2,706|      827|    3,298|    2,642|
|  강서서|        7|        8|       13|       13|      262|      191|    2,096|    1,260|    3,207|    2,718|
+--------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+
only showing top 20 rows

In [6]:
df.printSchema()  #절도 발생~폭력 검거 형변환 필요

root
 |-- 관서명: string (nullable = true)
 |-- 살인 발생: integer (nullable = true)
 |-- 살인 검거: integer (nullable = true)
 |-- 강도 발생: integer (nullable = true)
 |-- 강도 검거: integer (nullable = true)
 |-- 강간 발생: integer (nullable = true)
 |-- 강간 검거: integer (nullable = true)
 |-- 절도 발생: string (nullable = true)
 |-- 절도 검거: string (nullable = true)
 |-- 폭력 발생: string (nullable = true)
 |-- 폭력 검거: string (nullable = true)

In [7]:
 type(df)

pyspark.sql.dataframe.DataFrame

In [8]:
df.head(5)

[Row(관서명='중부서', 살인 발생=2, 살인 검거=2, 강도 발생=3, 강도 검거=2, 강간 발생=105, 강간 검거=65, 절도 발생='1,395', 절도 검거='477', 폭력 발생='1,355', 폭력 검거='1,170'),
 Row(관서명='종로서', 살인 발생=3, 살인 검거=3, 강도 발생=6, 강도 검거=5, 강간 발생=115, 강간 검거=98, 절도 발생='1,070', 절도 검거='413', 폭력 발생='1,278', 폭력 검거='1,070'),
 Row(관서명='남대문서', 살인 발생=1, 살인 검거=0, 강도 발생=6, 강도 검거=4, 강간 발생=65, 강간 검거=46, 절도 발생='1,153', 절도 검거='382', 폭력 발생='869', 폭력 검거='794'),
 Row(관서명='서대문서', 살인 발생=2, 살인 검거=2, 강도 발생=5, 강도 검거=4, 강간 발생=154, 강간 검거=124, 절도 발생='1,812', 절도 검거='738', 폭력 발생='2,056', 폭력 검거='1,711'),
 Row(관서명='혜화서', 살인 발생=3, 살인 검거=2, 강도 발생=5, 강도 검거=4, 강간 발생=96, 강간 검거=63, 절도 발생='1,114', 절도 검거='424', 폭력 발생='1,015', 폭력 검거='861')]

In [9]:
df.count() #전체 row 갯수

31

In [10]:
df.columns

['관서명',
 '살인 발생',
 '살인 검거',
 '강도 발생',
 '강도 검거',
 '강간 발생',
 '강간 검거',
 '절도 발생',
 '절도 검거',
 '폭력 발생',
 '폭력 검거']

In [11]:
df.shape #error

AttributeError: 'DataFrame' object has no attribute 'shape'

In [12]:
print('행', df.count(), '열', len(df.columns))

행 31 열 11

In [ ]:
#원 데이터를 그대로 topandas()할 시 메모리 다운될 수 있기 때문에 조심

In [13]:
df.describe().toPandas() #quantile값은 없음

,summary,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거
0,count,31,31,31,31,31,31,31,31,31,31,31
1,mean,None,5.258064516129032,4.935483870967742,8.903225806451612,8.161290322580646,175.7741935483871,131.96774193548387,814.25,638.1428571428571,708.0,746.5
2,stddev,None,3.6052530372174423,3.203492717550306,4.9352800576372395,5.710205916856522,85.58025850136987,56.59003673849767,123.27577485729573,224.73963771863822,227.6883835420683,172.61614447476612
3,min,강남서,1,0,1,1,59,46,"1,063","1,129","1,015","1,015"
4,max,혜화서,14,12,22,26,334,247,953,984,869,861

In [14]:
type(df.관서명)

pyspark.sql.column.Column

In [15]:
type(df['관서명'])

pyspark.sql.column.Column

#### pandas
    df[['관서명', '강도 발생']]

In [16]:
df.select('관서명', '강도 발생').show() #default n=20
#spark 데이터에는 index 없음

+--------+---------+
|  관서명|강도 발생|
+--------+---------+
|  중부서|        3|
|  종로서|        6|
|남대문서|        6|
|서대문서|        5|
|  혜화서|        5|
|  용산서|       14|
|  성북서|        2|
|동대문서|       13|
|  마포서|       14|
|영등포서|       22|
|  성동서|        9|
|  동작서|        9|
|  광진서|       14|
|  서부서|        2|
|  강북서|       14|
|  금천서|        6|
|  중랑서|       11|
|  강남서|       15|
|  관악서|       12|
|  강서서|       13|
+--------+---------+
only showing top 20 rows

In [17]:
df.orderBy('관서명').show(df.count()) #원본 길이만큼

+--------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+
|  관서명|살인 발생|살인 검거|강도 발생|강도 검거|강간 발생|강간 검거|절도 발생|절도 검거|폭력 발생|폭력 검거|
+--------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+
|  강남서|        3|        3|       15|       12|      300|      225|    2,411|      984|    2,465|    2,146|
|  강동서|        4|        3|        6|        8|      156|      123|    2,366|      789|    2,712|    2,248|
|  강북서|        7|        8|       14|       13|      153|      126|    1,434|      618|    2,649|    2,348|
|  강서서|        7|        8|       13|       13|      262|      191|    2,096|    1,260|    3,207|    2,718|
|  관악서|        9|        8|       12|       14|      320|      221|    2,706|      827|    3,298|    2,642|
|  광진서|        4|        4|       14|       26|      240|      220|    3,026|    1,277|    2,625|    2,180|
|  구로서|        8|        6|       15|       11|      281|      164|    2,335|      889|    3,007|    2,432|
|  금천서|        3|        4|        6|        6|      151|      122|    1,567|      888|    2,054|    1,776|
|남대문서|        1|        0|        6|        4|       65|       46|    1,153|      382|      869|      794|
|  노원서|       10|       10|        7|        7|      197|      121|    2,193|      801|    2,723|    2,329|
|  도봉서|        3|        3|        9|       10|      102|      106|    1,063|      478|    1,487|    1,303|
|동대문서|        5|        5|       13|       13|      173|      146|    1,981|      814|    2,548|    2,227|
|  동작서|        5|        5|        9|        5|      285|      139|    1,865|      661|    1,910|    1,587|
|  마포서|        8|        8|       14|       10|      294|      247|    2,555|      813|    2,983|    2,519|
|  방배서|        1|        2|        1|        1|       59|       56|      653|      186|      547|      491|
|서대문서|        2|        2|        5|        4|      154|      124|    1,812|      738|    2,056|    1,711|
|  서부서|        2|        2|        2|        1|       70|       59|      819|      293|    1,192|    1,038|
|  서초서|        7|        4|        8|        5|      334|      193|    1,982|      905|    1,852|    1,607|
|  성동서|        4|        4|        9|        8|      126|      119|    1,607|      597|    1,612|    1,395|
|  성북서|        2|        2|        2|        1|       86|       71|      953|      409|    1,194|    1,015|
|  송파서|       11|       10|       13|       10|      220|      178|    3,239|    1,129|    3,295|    2,786|
|  수서서|       10|        7|        6|        6|      149|      124|    1,439|      666|    1,819|    1,559|
|  양천서|        3|        5|        6|        3|      120|      105|    1,890|      672|    2,509|    2,030|
|영등포서|       14|       12|       22|       20|      295|      183|    2,964|      978|    3,572|    2,961|
|  용산서|        5|        5|       14|       14|      194|      173|    1,557|      587|    2,050|    1,704|
|  은평서|        1|        1|        7|        5|       96|       82|    1,095|      418|    1,461|    1,268|
|  종로서|        3|        3|        6|        5|      115|       98|    1,070|      413|    1,278|    1,070|
|  종암서|        3|        3|        3|        3|       64|       53|      832|      332|    1,015|      840|
|  중랑서|       13|       12|       11|        9|      187|      148|    2,135|      829|    2,847|    2,407|
|  중부서|        2|        2|        3|        2|      105|       65|    1,395|      477|    1,355|    1,170|
|  혜화서|        3|        2|        5|        4|       96|       63|    1,114|      424|    1,015|      861|
+--------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+

In [18]:
df2 = df.select('관서명', '강도 발생').orderBy('관서명')
df2.show()

+--------+---------+
|  관서명|강도 발생|
+--------+---------+
|  강남서|       15|
|  강동서|        6|
|  강북서|       14|
|  강서서|       13|
|  관악서|       12|
|  광진서|       14|
|  구로서|       15|
|  금천서|        6|
|남대문서|        6|
|  노원서|        7|
|  도봉서|        9|
|동대문서|       13|
|  동작서|        9|
|  마포서|       14|
|  방배서|        1|
|서대문서|        5|
|  서부서|        2|
|  서초서|        8|
|  성동서|        9|
|  성북서|        2|
+--------+---------+
only showing top 20 rows

In [19]:
df.where("`관서명`=='강북서'").show() #한글 컬럼 backtick은 where 구문에서만 / = 도 되고 == 도 됨

+------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+
|관서명|살인 발생|살인 검거|강도 발생|강도 검거|강간 발생|강간 검거|절도 발생|절도 검거|폭력 발생|폭력 검거|
+------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+
|강북서|        7|        8|       14|       13|      153|      126|    1,434|      618|    2,649|    2,348|
+------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+

#### pandas
    df[ df['관서명']=='강북서' ]
    df.query("관서명=='강북서'")

In [20]:
df.where("`살인 발생`>5").show()

+--------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+
|  관서명|살인 발생|살인 검거|강도 발생|강도 검거|강간 발생|강간 검거|절도 발생|절도 검거|폭력 발생|폭력 검거|
+--------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+
|  마포서|        8|        8|       14|       10|      294|      247|    2,555|      813|    2,983|    2,519|
|영등포서|       14|       12|       22|       20|      295|      183|    2,964|      978|    3,572|    2,961|
|  강북서|        7|        8|       14|       13|      153|      126|    1,434|      618|    2,649|    2,348|
|  중랑서|       13|       12|       11|        9|      187|      148|    2,135|      829|    2,847|    2,407|
|  관악서|        9|        8|       12|       14|      320|      221|    2,706|      827|    3,298|    2,642|
|  강서서|        7|        8|       13|       13|      262|      191|    2,096|    1,260|    3,207|    2,718|
|  구로서|        8|        6|       15|       11|      281|      164|    2,335|      889|    3,007|    2,432|
|  서초서|        7|        4|        8|        5|      334|      193|    1,982|      905|    1,852|    1,607|
|  송파서|       11|       10|       13|       10|      220|      178|    3,239|    1,129|    3,295|    2,786|
|  노원서|       10|       10|        7|        7|      197|      121|    2,193|      801|    2,723|    2,329|
|  수서서|       10|        7|        6|        6|      149|      124|    1,439|      666|    1,819|    1,559|
+--------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+

In [21]:
#살인 발생이 10건 이상인 관서명, 살인 발생, 살인 검거 출력
df.select('관서명', '살인 발생', '살인 검거').where("`살인 발생`>10").show()

+--------+---------+---------+
|  관서명|살인 발생|살인 검거|
+--------+---------+---------+
|영등포서|       14|       12|
|  중랑서|       13|       12|
|  송파서|       11|       10|
+--------+---------+---------+

In [22]:
#df[ df['관서명'].isin( ['중부서', '종로서'] ) ]
df.where("`관서명` in('중부서', '종로서')").show()

+------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+
|관서명|살인 발생|살인 검거|강도 발생|강도 검거|강간 발생|강간 검거|절도 발생|절도 검거|폭력 발생|폭력 검거|
+------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+
|중부서|        2|        2|        3|        2|      105|       65|    1,395|      477|    1,355|    1,170|
|종로서|        3|        3|        6|        5|      115|       98|    1,070|      413|    1,278|    1,070|
+------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+

In [23]:
#df[ df['살인 발생'].between(5, 10) ]
df.where("`강도 발생` between 5 and 10").show()

+--------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+
|  관서명|살인 발생|살인 검거|강도 발생|강도 검거|강간 발생|강간 검거|절도 발생|절도 검거|폭력 발생|폭력 검거|
+--------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+
|  종로서|        3|        3|        6|        5|      115|       98|    1,070|      413|    1,278|    1,070|
|남대문서|        1|        0|        6|        4|       65|       46|    1,153|      382|      869|      794|
|서대문서|        2|        2|        5|        4|      154|      124|    1,812|      738|    2,056|    1,711|
|  혜화서|        3|        2|        5|        4|       96|       63|    1,114|      424|    1,015|      861|
|  성동서|        4|        4|        9|        8|      126|      119|    1,607|      597|    1,612|    1,395|
|  동작서|        5|        5|        9|        5|      285|      139|    1,865|      661|    1,910|    1,587|
|  금천서|        3|        4|        6|        6|      151|      122|    1,567|      888|    2,054|    1,776|
|  강동서|        4|        3|        6|        8|      156|      123|    2,366|      789|    2,712|    2,248|
|  서초서|        7|        4|        8|        5|      334|      193|    1,982|      905|    1,852|    1,607|
|  양천서|        3|        5|        6|        3|      120|      105|    1,890|      672|    2,509|    2,030|
|  노원서|       10|       10|        7|        7|      197|      121|    2,193|      801|    2,723|    2,329|
|  은평서|        1|        1|        7|        5|       96|       82|    1,095|      418|    1,461|    1,268|
|  도봉서|        3|        3|        9|       10|      102|      106|    1,063|      478|    1,487|    1,303|
|  수서서|       10|        7|        6|        6|      149|      124|    1,439|      666|    1,819|    1,559|
+--------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+

In [25]:
#df = df.drop('폭력 발생', '폭력 검거')
df.drop('폭력 발생', '폭력 검거').show()

+--------+---------+---------+---------+---------+---------+---------+---------+---------+
|  관서명|살인 발생|살인 검거|강도 발생|강도 검거|강간 발생|강간 검거|절도 발생|절도 검거|
+--------+---------+---------+---------+---------+---------+---------+---------+---------+
|  중부서|        2|        2|        3|        2|      105|       65|    1,395|      477|
|  종로서|        3|        3|        6|        5|      115|       98|    1,070|      413|
|남대문서|        1|        0|        6|        4|       65|       46|    1,153|      382|
|서대문서|        2|        2|        5|        4|      154|      124|    1,812|      738|
|  혜화서|        3|        2|        5|        4|       96|       63|    1,114|      424|
|  용산서|        5|        5|       14|       14|      194|      173|    1,557|      587|
|  성북서|        2|        2|        2|        1|       86|       71|      953|      409|
|동대문서|        5|        5|       13|       13|      173|      146|    1,981|      814|
|  마포서|        8|        8|       14|       10|      294|      247|    2,555|      813|
|영등포서|       14|       12|       22|       20|      295|      183|    2,964|      978|
|  성동서|        4|        4|        9|        8|      126|      119|    1,607|      597|
|  동작서|        5|        5|        9|        5|      285|      139|    1,865|      661|
|  광진서|        4|        4|       14|       26|      240|      220|    3,026|    1,277|
|  서부서|        2|        2|        2|        1|       70|       59|      819|      293|
|  강북서|        7|        8|       14|       13|      153|      126|    1,434|      618|
|  금천서|        3|        4|        6|        6|      151|      122|    1,567|      888|
|  중랑서|       13|       12|       11|        9|      187|      148|    2,135|      829|
|  강남서|        3|        3|       15|       12|      300|      225|    2,411|      984|
|  관악서|        9|        8|       12|       14|      320|      221|    2,706|      827|
|  강서서|        7|        8|       13|       13|      262|      191|    2,096|    1,260|
+--------+---------+---------+---------+---------+---------+---------+---------+---------+
only showing top 20 rows

In [27]:
#df['test'] = df['폭력 발생']
df.withColumn('test', df['폭력 발생']).toPandas()

,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,test
0,중부서,2,2,3,2,105,65,"1,395",477,"1,355","1,170","1,355"
1,종로서,3,3,6,5,115,98,"1,070",413,"1,278","1,070","1,278"
2,남대문서,1,0,6,4,65,46,"1,153",382,869,794,869
3,서대문서,2,2,5,4,154,124,"1,812",738,"2,056","1,711","2,056"
4,혜화서,3,2,5,4,96,63,"1,114",424,"1,015",861,"1,015"
5,용산서,5,5,14,14,194,173,"1,557",587,"2,050","1,704","2,050"
6,성북서,2,2,2,1,86,71,953,409,"1,194","1,015","1,194"
7,동대문서,5,5,13,13,173,146,"1,981",814,"2,548","2,227","2,548"
8,마포서,8,8,14,10,294,247,"2,555",813,"2,983","2,519","2,983"
9,영등포서,14,12,22,20,295,183,"2,964",978,"3,572","2,961","3,572"
10,성동서,4,4,9,8,126,119,"1,607",597,"1,612","1,395","1,612"
11,동작서,5,5,9,5,285,139,"1,865",661,"1,910","1,587","1,910"
12,광진서,4,4,14,26,240,220,"3,026","1,277","2,625","2,180","2,625"
13,서부서,2,2,2,1,70,59,819,293,"1,192","1,038","1,192"
14,강북서,7,8,14,13,153,126,"1,434",618,"2,649","2,348","2,649"
15,금천서,3,4,6,6,151,122,"1,567",888,"2,054","1,776","2,054"
16,중랑서,13,12,11,9,187,148,"2,135",829,"2,847","2,407","2,847"
17,강남서,3,3,15,12,300,225,"2,411",984,"2,465","2,146","2,465"
18,관악서,9,8,12,14,320,221,"2,706",827,"3,298","2,642","3,298"
19,강서서,7,8,13,13,262,191,"2,096","1,260","3,207","2,718","3,207"
20,강동서,4,3,6,8,156,123,"2,366",789,"2,712","2,248","2,712"
21,종암서,3,3,3,3,64,53,832,332,"1,015",840,"1,015"
22,구로서,8,6,15,11,281,164,"2,335",889,"3,007","2,432","3,007"
23,서초서,7,4,8,5,334,193,"1,982",905,"1,852","1,607","1,852"
24,양천서,3,5,6,3,120,105,"1,890",672,"2,509","2,030","2,509"
25,송파서,11,10,13,10,220,178,"3,239","1,129","3,295","2,786","3,295"
26,노원서,10,10,7,7,197,121,"2,193",801,"2,723","2,329","2,723"
27,방배서,1,2,1,1,59,56,653,186,547,491,547
28,은평서,1,1,7,5,96,82,"1,095",418,"1,461","1,268","1,461"
29,도봉서,3,3,9,10,102,106,"1,063",478,"1,487","1,303","1,487"
30,수서서,10,7,6,6,149,124,"1,439",666,"1,819","1,559","1,819"

In [28]:
from pyspark.sql.functions import when, udf, col, regexp_replace
from pyspark.sql.types import DoubleType,IntegerType, StringType

In [ ]:
# def fn(v):
#     if v>=10:
#         return '많음'
#     elif v>=5:
#         return '보통'
#     else:
#         return '적음'
# return fn

#### pandas
    df['살인 정도'] = df['살인 발생'].apply(fn)

In [29]:
df.withColumn('살인 정도', when(df['살인 발생']>=10, 
                            '많음').when(df['살인 발생']>=5, '보통').otherwise('적음') ).toPandas()

,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,살인 정도
0,중부서,2,2,3,2,105,65,"1,395",477,"1,355","1,170",적음
1,종로서,3,3,6,5,115,98,"1,070",413,"1,278","1,070",적음
2,남대문서,1,0,6,4,65,46,"1,153",382,869,794,적음
3,서대문서,2,2,5,4,154,124,"1,812",738,"2,056","1,711",적음
4,혜화서,3,2,5,4,96,63,"1,114",424,"1,015",861,적음
5,용산서,5,5,14,14,194,173,"1,557",587,"2,050","1,704",보통
6,성북서,2,2,2,1,86,71,953,409,"1,194","1,015",적음
7,동대문서,5,5,13,13,173,146,"1,981",814,"2,548","2,227",보통
8,마포서,8,8,14,10,294,247,"2,555",813,"2,983","2,519",보통
9,영등포서,14,12,22,20,295,183,"2,964",978,"3,572","2,961",많음
10,성동서,4,4,9,8,126,119,"1,607",597,"1,612","1,395",적음
11,동작서,5,5,9,5,285,139,"1,865",661,"1,910","1,587",보통
12,광진서,4,4,14,26,240,220,"3,026","1,277","2,625","2,180",적음
13,서부서,2,2,2,1,70,59,819,293,"1,192","1,038",적음
14,강북서,7,8,14,13,153,126,"1,434",618,"2,649","2,348",보통
15,금천서,3,4,6,6,151,122,"1,567",888,"2,054","1,776",적음
16,중랑서,13,12,11,9,187,148,"2,135",829,"2,847","2,407",많음
17,강남서,3,3,15,12,300,225,"2,411",984,"2,465","2,146",적음
18,관악서,9,8,12,14,320,221,"2,706",827,"3,298","2,642",보통
19,강서서,7,8,13,13,262,191,"2,096","1,260","3,207","2,718",보통
20,강동서,4,3,6,8,156,123,"2,366",789,"2,712","2,248",적음
21,종암서,3,3,3,3,64,53,832,332,"1,015",840,적음
22,구로서,8,6,15,11,281,164,"2,335",889,"3,007","2,432",보통
23,서초서,7,4,8,5,334,193,"1,982",905,"1,852","1,607",보통
24,양천서,3,5,6,3,120,105,"1,890",672,"2,509","2,030",적음
25,송파서,11,10,13,10,220,178,"3,239","1,129","3,295","2,786",많음
26,노원서,10,10,7,7,197,121,"2,193",801,"2,723","2,329",많음
27,방배서,1,2,1,1,59,56,653,186,547,491,적음
28,은평서,1,1,7,5,96,82,"1,095",418,"1,461","1,268",적음
29,도봉서,3,3,9,10,102,106,"1,063",478,"1,487","1,303",적음
30,수서서,10,7,6,6,149,124,"1,439",666,"1,819","1,559",많음

In [30]:
# ff = udf(fn) / 함수 적용 / 조건 3개 이상이면 함수 따로 만들어야
ff = udf(lambda v:'많음' if v>=10 else '적음')
df.withColumn('살인 정도1', ff(df['살인 발생'])).toPandas()

,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,살인 정도1
0,중부서,2,2,3,2,105,65,"1,395",477,"1,355","1,170",적음
1,종로서,3,3,6,5,115,98,"1,070",413,"1,278","1,070",적음
2,남대문서,1,0,6,4,65,46,"1,153",382,869,794,적음
3,서대문서,2,2,5,4,154,124,"1,812",738,"2,056","1,711",적음
4,혜화서,3,2,5,4,96,63,"1,114",424,"1,015",861,적음
5,용산서,5,5,14,14,194,173,"1,557",587,"2,050","1,704",적음
6,성북서,2,2,2,1,86,71,953,409,"1,194","1,015",적음
7,동대문서,5,5,13,13,173,146,"1,981",814,"2,548","2,227",적음
8,마포서,8,8,14,10,294,247,"2,555",813,"2,983","2,519",적음
9,영등포서,14,12,22,20,295,183,"2,964",978,"3,572","2,961",많음
10,성동서,4,4,9,8,126,119,"1,607",597,"1,612","1,395",적음
11,동작서,5,5,9,5,285,139,"1,865",661,"1,910","1,587",적음
12,광진서,4,4,14,26,240,220,"3,026","1,277","2,625","2,180",적음
13,서부서,2,2,2,1,70,59,819,293,"1,192","1,038",적음
14,강북서,7,8,14,13,153,126,"1,434",618,"2,649","2,348",적음
15,금천서,3,4,6,6,151,122,"1,567",888,"2,054","1,776",적음
16,중랑서,13,12,11,9,187,148,"2,135",829,"2,847","2,407",많음
17,강남서,3,3,15,12,300,225,"2,411",984,"2,465","2,146",적음
18,관악서,9,8,12,14,320,221,"2,706",827,"3,298","2,642",적음
19,강서서,7,8,13,13,262,191,"2,096","1,260","3,207","2,718",적음
20,강동서,4,3,6,8,156,123,"2,366",789,"2,712","2,248",적음
21,종암서,3,3,3,3,64,53,832,332,"1,015",840,적음
22,구로서,8,6,15,11,281,164,"2,335",889,"3,007","2,432",적음
23,서초서,7,4,8,5,334,193,"1,982",905,"1,852","1,607",적음
24,양천서,3,5,6,3,120,105,"1,890",672,"2,509","2,030",적음
25,송파서,11,10,13,10,220,178,"3,239","1,129","3,295","2,786",많음
26,노원서,10,10,7,7,197,121,"2,193",801,"2,723","2,329",많음
27,방배서,1,2,1,1,59,56,653,186,547,491,적음
28,은평서,1,1,7,5,96,82,"1,095",418,"1,461","1,268",적음
29,도봉서,3,3,9,10,102,106,"1,063",478,"1,487","1,303",적음
30,수서서,10,7,6,6,149,124,"1,439",666,"1,819","1,559",많음

In [31]:
df.withColumn('절도 발생1', regexp_replace('절도 발생', ',', '') ).toPandas()

,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,절도 발생1
0,중부서,2,2,3,2,105,65,"1,395",477,"1,355","1,170",1395
1,종로서,3,3,6,5,115,98,"1,070",413,"1,278","1,070",1070
2,남대문서,1,0,6,4,65,46,"1,153",382,869,794,1153
3,서대문서,2,2,5,4,154,124,"1,812",738,"2,056","1,711",1812
4,혜화서,3,2,5,4,96,63,"1,114",424,"1,015",861,1114
5,용산서,5,5,14,14,194,173,"1,557",587,"2,050","1,704",1557
6,성북서,2,2,2,1,86,71,953,409,"1,194","1,015",953
7,동대문서,5,5,13,13,173,146,"1,981",814,"2,548","2,227",1981
8,마포서,8,8,14,10,294,247,"2,555",813,"2,983","2,519",2555
9,영등포서,14,12,22,20,295,183,"2,964",978,"3,572","2,961",2964
10,성동서,4,4,9,8,126,119,"1,607",597,"1,612","1,395",1607
11,동작서,5,5,9,5,285,139,"1,865",661,"1,910","1,587",1865
12,광진서,4,4,14,26,240,220,"3,026","1,277","2,625","2,180",3026
13,서부서,2,2,2,1,70,59,819,293,"1,192","1,038",819
14,강북서,7,8,14,13,153,126,"1,434",618,"2,649","2,348",1434
15,금천서,3,4,6,6,151,122,"1,567",888,"2,054","1,776",1567
16,중랑서,13,12,11,9,187,148,"2,135",829,"2,847","2,407",2135
17,강남서,3,3,15,12,300,225,"2,411",984,"2,465","2,146",2411
18,관악서,9,8,12,14,320,221,"2,706",827,"3,298","2,642",2706
19,강서서,7,8,13,13,262,191,"2,096","1,260","3,207","2,718",2096
20,강동서,4,3,6,8,156,123,"2,366",789,"2,712","2,248",2366
21,종암서,3,3,3,3,64,53,832,332,"1,015",840,832
22,구로서,8,6,15,11,281,164,"2,335",889,"3,007","2,432",2335
23,서초서,7,4,8,5,334,193,"1,982",905,"1,852","1,607",1982
24,양천서,3,5,6,3,120,105,"1,890",672,"2,509","2,030",1890
25,송파서,11,10,13,10,220,178,"3,239","1,129","3,295","2,786",3239
26,노원서,10,10,7,7,197,121,"2,193",801,"2,723","2,329",2193
27,방배서,1,2,1,1,59,56,653,186,547,491,653
28,은평서,1,1,7,5,96,82,"1,095",418,"1,461","1,268",1095
29,도봉서,3,3,9,10,102,106,"1,063",478,"1,487","1,303",1063
30,수서서,10,7,6,6,149,124,"1,439",666,"1,819","1,559",1439

In [32]:
df = df.withColumn('절도 발생1', regexp_replace('절도 발생', ',', '') )

In [35]:
df = df.withColumn('절도 발생1', df['절도 발생1'].cast(IntegerType() ) ) #string -> integer

In [37]:
df = df.withColumn('절도 발생', regexp_replace('절도 발생', ',', '') ).withColumn(
'절도 검거', regexp_replace('절도 검거', ',', '') ).withColumn(
'폭력 발생', regexp_replace('폭력 발생', ',', '') ).withColumn(
'폭력 검거', regexp_replace('폭력 검거', ',', '') )

In [40]:
df.toPandas()

,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,절도 발생1
0,중부서,2,2,3,2,105,65,1395,477,1355,1170,1395
1,종로서,3,3,6,5,115,98,1070,413,1278,1070,1070
2,남대문서,1,0,6,4,65,46,1153,382,869,794,1153
3,서대문서,2,2,5,4,154,124,1812,738,2056,1711,1812
4,혜화서,3,2,5,4,96,63,1114,424,1015,861,1114
5,용산서,5,5,14,14,194,173,1557,587,2050,1704,1557
6,성북서,2,2,2,1,86,71,953,409,1194,1015,953
7,동대문서,5,5,13,13,173,146,1981,814,2548,2227,1981
8,마포서,8,8,14,10,294,247,2555,813,2983,2519,2555
9,영등포서,14,12,22,20,295,183,2964,978,3572,2961,2964
10,성동서,4,4,9,8,126,119,1607,597,1612,1395,1607
11,동작서,5,5,9,5,285,139,1865,661,1910,1587,1865
12,광진서,4,4,14,26,240,220,3026,1277,2625,2180,3026
13,서부서,2,2,2,1,70,59,819,293,1192,1038,819
14,강북서,7,8,14,13,153,126,1434,618,2649,2348,1434
15,금천서,3,4,6,6,151,122,1567,888,2054,1776,1567
16,중랑서,13,12,11,9,187,148,2135,829,2847,2407,2135
17,강남서,3,3,15,12,300,225,2411,984,2465,2146,2411
18,관악서,9,8,12,14,320,221,2706,827,3298,2642,2706
19,강서서,7,8,13,13,262,191,2096,1260,3207,2718,2096
20,강동서,4,3,6,8,156,123,2366,789,2712,2248,2366
21,종암서,3,3,3,3,64,53,832,332,1015,840,832
22,구로서,8,6,15,11,281,164,2335,889,3007,2432,2335
23,서초서,7,4,8,5,334,193,1982,905,1852,1607,1982
24,양천서,3,5,6,3,120,105,1890,672,2509,2030,1890
25,송파서,11,10,13,10,220,178,3239,1129,3295,2786,3239
26,노원서,10,10,7,7,197,121,2193,801,2723,2329,2193
27,방배서,1,2,1,1,59,56,653,186,547,491,653
28,은평서,1,1,7,5,96,82,1095,418,1461,1268,1095
29,도봉서,3,3,9,10,102,106,1063,478,1487,1303,1063
30,수서서,10,7,6,6,149,124,1439,666,1819,1559,1439

In [41]:
sc.stop()